# Generated by Django 3.1.2 on 2020-10-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signalling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'siren'), ('2', 'speaker')], max_length=25, verbose_name='Type_of_signalling')),
                ('address', models.CharField(max_length=255, verbose_name='Address with signalling')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('coverage_area', models.IntegerField(verbose_name='Coverage area')),
            ],
        ),
    ]
